"""initial

Revision ID: 33b2597537e5
Revises: 
Create Date: 2025-11-22 01:23:12.311994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '33b2597537e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_date',
    sa.Column('date_key', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('dia_da_semana', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('nome_do_mes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('flag_feriado', sa.Boolean(), nullable=False),
    sa.Column('flag_fim_de_semana', sa.Boolean(), nullable=False),
    sa.Column('flag_dia_de_semana', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date_key')
    )
    op.create_table('dim_metodo_pagamento',
    sa.Column('metodo_pagamento_key', sa.Integer(), nullable=False),
    sa.Column('tipo_metodo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('metodo_pagamento_key')
    )
    op.create_table('dim_produto',
    sa.Column('produto_key', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categoria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('safra', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('regiao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('produto_key')
    )
    op.create_table('dim_produto_categoria',
    sa.Column('produto_categoria_key', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('produto_categoria_key')
    )
    op.create_table('dim_regiao',
    sa.Column('regiao_key', sa.Integer(), nullable=False),
    sa.Column('nome_regiao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('regiao_key')
    )
    op.create_table('dim_source',
    sa.Column('source_key', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('source_key')
    )
    op.create_table('dim_tipo_sentimento',
    sa.Column('tipo_sentimento_key', sa.Integer(), nullable=False),
    sa.Column('sentimento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('classificacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('tipo_sentimento_key')
    )
    op.create_table('dim_utilizador',
    sa.Column('utilizador_key', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('regiao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('utilizador_key')
    )
    op.create_table('ft_sentimento',
    sa.Column('sentimento_key', sa.Integer(), nullable=False),
    sa.Column('sentimento_date_key', sa.Integer(), nullable=False),
    sa.Column('utilizador_key', sa.Integer(), nullable=False),
    sa.Column('tipo_sentimento_key', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sentimento_date_key'], ['dim_date.date_key'], ),
    sa.ForeignKeyConstraint(['source_key'], ['dim_source.source_key'], ),
    sa.ForeignKeyConstraint(['tipo_sentimento_key'], ['dim_tipo_sentimento.tipo_sentimento_key'], ),
    sa.ForeignKeyConstraint(['utilizador_key'], ['dim_utilizador.utilizador_key'], ),
    sa.PrimaryKeyConstraint('sentimento_key', 'sentimento_date_key', 'utilizador_key', 'tipo_sentimento_key', 'source_key')
    )
    op.create_table('ft_vendas',
    sa.Column('venda_key', sa.Integer(), nullable=False),
    sa.Column('venda_date_key', sa.Integer(), nullable=False),
    sa.Column('utilizador_key', sa.Integer(), nullable=False),
    sa.Column('produto_key', sa.Integer(), nullable=False),
    sa.Column('produto_categoria_key', sa.Integer(), nullable=False),
    sa.Column('metodo_pagamento_key', sa.Integer(), nullable=False),
    sa.Column('valor_venda', sa.Float(), nullable=False),
    sa.Column('valor_desconto', sa.Float(), nullable=False),
    sa.Column('valor_iva', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['metodo_pagamento_key'], ['dim_metodo_pagamento.metodo_pagamento_key'], ),
    sa.ForeignKeyConstraint(['produto_categoria_key'], ['dim_produto_categoria.produto_categoria_key'], ),
    sa.ForeignKeyConstraint(['produto_key'], ['dim_produto.produto_key'], ),
    sa.ForeignKeyConstraint(['utilizador_key'], ['dim_utilizador.utilizador_key'], ),
    sa.ForeignKeyConstraint(['venda_date_key'], ['dim_date.date_key'], ),
    sa.PrimaryKeyConstraint('venda_key', 'venda_date_key', 'utilizador_key', 'produto_key', 'produto_categoria_key', 'metodo_pagamento_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ft_vendas')
    op.drop_table('ft_sentimento')
    op.drop_table('dim_utilizador')
    op.drop_table('dim_tipo_sentimento')
    op.drop_table('dim_source')
    op.drop_table('dim_regiao')
    op.drop_table('dim_produto_categoria')
    op.drop_table('dim_produto')
    op.drop_table('dim_metodo_pagamento')
    op.drop_table('dim_date')
    # ### end Alembic commands ###
